/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/kt-comps/kt-top copy.vue')['default']
    KtBottom: typeof import('./components/kt-comps/kt-bottom.vue')['default']
    KtChart: typeof import('./components/kt-comps/kt-chart.vue')['default']
    KtEchart: typeof import('./components/kt-comps/kt-echart.vue')['default']
    KtLeft: typeof import('./components/kt-comps/kt-left.vue')['default']
    KtRight: typeof import('./components/kt-comps/kt-right.vue')['default']
    KtTop: typeof import('./components/kt-comps/kt-top.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
