/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CusFooter: typeof import('./components/cus-comps/cus-footer.vue')['default']
    CusHeader: typeof import('./components/cus-comps/cus-header.vue')['default']
    KtAnimeScroll: typeof import('./components/kt-comps/kt-anime-scroll.vue')['default']
    KtBottom: typeof import('./components/kt-comps/kt-bottom.vue')['default']
    KtChart: typeof import('./components/kt-comps/kt-chart.vue')['default']
    KtDateTimer: typeof import('./components/kt-comps/kt-date-timer.vue')['default']
    KtLeft: typeof import('./components/kt-comps/kt-left.vue')['default']
    KtRight: typeof import('./components/kt-comps/kt-right.vue')['default']
    KtTable: typeof import('./components/kt-comps/kt-table.vue')['default']
    KtToggleImg: typeof import('./components/kt-comps/kt-toggle-img.vue')['default']
    KtTop: typeof import('./components/kt-comps/kt-top.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
